# Dockerfile.server
FROM python:3.9-slim

WORKDIR /app

# Install required packages
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy server code
COPY opcua_server.py .

# Expose OPC UA port
EXPOSE 4840

# Run the server
CMD ["python", "opcua_server_tls.py"]