name: BACnet Simulation CI/CD
on:
  push:
    branches:
      - main
      - develop
    pull_request:
      branches:
        - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup python environment
        uses: action/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install -upgrade pip
          pip install -r requirements.txt

      - name: Run test
        run: |
          python -m unittest discover

      # The rest of the code is optional
      # - name: Log in to Docker Hub
      #   if: github.event_name == 'push'
      #   run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      #   env:
      #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      #     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build Docker image
      #   if: github.event_name == 'push'
      #   run: docker build -t bacnet-simulation:${{ github.sha }} .

      # - name: Push Docker image to Docker Hub
      #   if: github.event_name == 'push'
      #   run: docker push bacnet-simulation:${{ github.sha }}

      # # Optional: Run Docker container with tests
      # - name: Run Docker container with tests (Optional)
      #   if: github.event_name == 'pull_request'
      #   run: |
      #     docker-compose up --exit-code-from test-bacnet-simulation