services:
  server:
    build:
      context: ./modbus_server
      dockerfile: Dockerfile
    ports:
      - "5026:5026"
      - "15000:15000" # Expose Flask API port
    networks:
      - modbus-net
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - MODBUS_SERVER_IP=server
      - MODBUS_SERVER_PORT=5026
    restart: on-failure

    depends_on:
      - server # Ensure server starts first
    networks:
      - modbus-net

networks:
  modbus-net:
    driver: bridge