name: IoT Simulation CI/CD

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'bacnetsim/**'
  pull_request:
    branches:
      - main
    paths:
      - 'bacnetsim/**'

jobs:
  bacnet-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup python environment  
        uses: actions/setup-python@v5 
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r bacnetsim/requirements.txt

      - name: Run bacnet tests
        run: |
          python -m unittest discover bacnetsim  # Run tests for bacnetsim folder
