name: IoT Simulation CI/CD

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'bacnetsim/**'
      - 'snmpsim/**'
  pull_request:
    branches:
      - main
    paths:
      - 'bacnetsim/**'
      - 'snmpsim/**'

jobs:
  bacnet-build-and-test:
    if: ${{ contains(github.event.head_commit.message, 'bacnetsim') || contains(github.event.commits[*].modified, 'bacnetsim/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup python environment
        uses: action/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install -upgrade pip
          pip install -r requirements.txt

      - name: Run bacnet tests
        run: |
          python -m unittest discover bacnetsim  # Run tests for bacnetsim folder

  snmp-build-and-test:
    if: ${{ contains(github.event.head_commit.message, 'snmpsim') || contains(github.event.commits[*].modified, 'snmpsim/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup python environment
        uses: action/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install -upgrade pip
          pip install -r requirements.txt
