name: IoT Simulation CI/CD

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'bacnetsim/**'
      - 'snmpsim/**'
  pull_request:
    branches:
      - main
    paths:
      - 'bacnetsim/**'
      - 'snmpsim/**'

jobs:
  debug-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_bacnetsim: ${{ steps.changed-files.outputs.bacnetsim }}
      changed_snmpsim: ${{ steps.changed-files.outputs.snmpsim }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        run: |
          # Get the list of changed files
          CHANGED_FILES=$(git diff --name-only HEAD~1)
          echo "Changed files: $CHANGED_FILES"

          # Check if any files in bacnetsim/ or snmpsim/ were modified
          BACNETSIM_CHANGED=false
  bacnet-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r bacnetsim/requirements.txt
      - name: Run Bacnet tests
        run: |
          python -m unittest discover bacnetsim  # Run tests for bacnetsim folder

  snmp-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r snmpsim/requirements.txt
      - name: Run SNMP tests
        run: |
          python -m unittest discover snmpsim  # Run tests for snmpsim folder