name: IoT Simulation CI/CD

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'bacnetsim/**'
      - 'snmpsim/**'
  pull_request:
    branches:
      - main
    paths:
      - 'bacnetsim/**'
      - 'snmpsim/**'

jobs:
  debug-event:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Context
        run: echo "$GITHUB_CONTEXT" | jq .

  bacnet-build-and-test:
    if: ${{ fromJSON(string(github.event)).event_name == 'push' && contains(fromJSON(string(github.event)).push.changes.*.filename, 'bacnetsim/') || github.event_name == 'pull_request' && contains(github.event.pull_request.changed_files, 'bacnetsim/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r bacnetsim/requirements.txt
      - name: Run Bacnet tests
        run: |
          python -m unittest discover bacnetsim  # Run tests for bacnetsim folder

  snmp-build-and-test:
    if: ${{ fromJSON(string(github.event)).event_name == 'push' && contains(fromJSON(string(github.event)).push.changes.*.filename, 'snmpsim/') || github.event_name == 'pull_request' && contains(github.event.pull_request.changed_files, 'snmpsim/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r snmpsim/requirements.txt
      - name: Run SNMP tests
        run: |
          python -m unittest discover snmpsim  # Run tests for snmpsim folder