# name: IoT Simulation CI/CD

# on:
#   push:
#     branches:
#       - main
#       - develop
#     paths:
#       - 'bacnetsim/**'
#       - 'snmpsim/**'
#   pull_request:
#     branches:
#       - main
#     paths:
#       - 'bacnetsim/**'
#       - 'snmpsim/**'

# jobs:
#   bacnet-build-and-test:
#     if: ${{ contains(github.event.push.diffs.files, 'bacnetsim/') || github.event_name == 'pull_request' && contains(github.event.pull_request.changed_files, 'bacnetsim/') }}
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Setup python environment  
#         uses: actions/setup-python@v5 
#         with:
#           python-version: '3.9'

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r bacnetsim/requirements.txt

#       - name: Run bacnet tests
#         run: |
#           python -m unittest discover bacnetsim  # Run tests for bacnetsim folder

#   snmp-build-and-test:
#     if: ${{ startsWith(github.event.head_commit.message, 'snmpsim') || contains(join(github.event.commits.*.message, ', '), 'snmpsim') }}
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Setup python environment
#         uses: action/setup-python@v5
#         with:
#           python-version: '3.9'

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r smmpsim/requirements.txt